name: Build And Pushlish

on: 
  push:
    branches: [ main ]

jobs:

  build-with-maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode package
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ToolSetUserCenter
        path: output/ToolSetUserCenter.jar

  pull-to-docker-hub:

    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: ToolSetUserCenter
        path: package
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag toolset_usercenter:$(date +%s)